#!/usr/bin/env bash
# Structure-only check (no Aura binary required).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "=== Daedalus structure check ==="

required=(
  "README.md"
  "LICENSE"
  "notes/span-design.md"
  "notes/denseness-report.md"
  "notes/escape-log.md"
  "notes/host-residuals.md"
  "notes/roadmap.md"
  "prompts/GROK.md"
  "lib/README.md"
  "lib/daedalus-min.aura"
  "lib/netlist.aura"
  "lib/stamp.aura"
  "lib/solve.aura"
  "lib/probe.aura"
  "lib/measure.aura"
  "lib/step.aura"
  "lib/mc.aura"
  "lib/evolve.aura"
  "lib/topo.aura"
  "lib/spice.aura"
  "lib/native.aura"
  "lib/ffi.aura"
  "lib/buf.aura"
  "notes/buf-exchange.md"
  "native/daed_abi.h"
  "native/daed_solve.cpp"
  "native/CMakeLists.txt"
  "native/example_dense.c"
  "native/README.md"
  "scripts/build-native.sh"
  "scripts/check-native-abi.sh"
  "notes/spice-export.md"
  "lib/tran.aura"
  "lib/mutate-circuit.aura"
  "lib/agent.aura"
  "lib/viz.aura"
  "lib/schematic.aura"
  "lib/devices.aura"
  "lib/ir.aura"
  "lib/validate.aura"
  "lib/repair.aura"
  "lib/vision.aura"
  "notes/ir-schema.md"
  "prompts/schematic-extract.md"
  "projects/daedalus-core/SPEC.md"
  "examples/README.md"
  "examples/00-smoke/main.aura"
  "examples/00-smoke/README.md"
  "examples/01-voltage-divider/main.aura"
  "examples/01-voltage-divider/README.md"
  "examples/02-rc-lowpass/main.aura"
  "examples/02-rc-lowpass/README.md"
  "examples/03-mutate-resistor/main.aura"
  "examples/03-mutate-resistor/README.md"
  "examples/05-agent-autotune/main.aura"
  "examples/05-agent-autotune/README.md"
  "examples/06-viz-bidirectional/main.aura"
  "examples/06-viz-bidirectional/README.md"
  "examples/07-diode-op/main.aura"
  "examples/07-diode-op/README.md"
  "examples/08-bjt-ce/main.aura"
  "examples/08-bjt-ce/README.md"
  "examples/09-diode-clamp-tran/main.aura"
  "examples/09-diode-clamp-tran/README.md"
  "examples/10-vision-pipeline/main.aura"
  "examples/10-vision-pipeline/README.md"
  "examples/11-controlled-sources/main.aura"
  "examples/11-controlled-sources/README.md"
  "examples/12-linear-op-suite/main.aura"
  "examples/12-linear-op-suite/README.md"
  "examples/13-tran-suite/main.aura"
  "examples/13-tran-suite/README.md"
  "examples/14-mutate-rollback/main.aura"
  "examples/14-mutate-rollback/README.md"
  "examples/15-nr-helpers/main.aura"
  "examples/15-nr-helpers/README.md"
  "examples/16-nl-op-suite/main.aura"
  "examples/16-nl-op-suite/README.md"
  "examples/17-adapt-tran/main.aura"
  "examples/17-adapt-tran/README.md"
  "examples/18-mosfet/main.aura"
  "examples/18-mosfet/README.md"
  "examples/19-measure/main.aura"
  "examples/19-measure/README.md"
  "examples/20-converge-aids/main.aura"
  "examples/20-converge-aids/README.md"
  "examples/21-step-temp/main.aura"
  "examples/21-step-temp/README.md"
  "examples/22-monte-carlo/main.aura"
  "examples/22-monte-carlo/README.md"
  "examples/23-agent-evolve/main.aura"
  "examples/23-agent-evolve/README.md"
  "examples/24-topo-mutate/main.aura"
  "examples/24-topo-mutate/README.md"
  "examples/25-spice-export/main.aura"
  "examples/25-spice-export/README.md"
  "examples/26-native-hotswap/main.aura"
  "examples/26-native-hotswap/README.md"
  "examples/27-ffi-bind/main.aura"
  "examples/27-ffi-bind/README.md"
  "examples/28-heph-wrap/main.aura"
  "examples/28-heph-wrap/README.md"
  "examples/29-buf-exchange/main.aura"
  "examples/29-buf-exchange/README.md"
  "examples/30-native-hotswap-demo/main.aura"
  "examples/30-native-hotswap-demo/README.md"
  "examples/31-native-op-nr/main.aura"
  "examples/31-native-op-nr/README.md"
  "scripts/run-hotswap-demo.sh"
  "scripts/roundtrip-spice.sh"
  "examples/16-nl-op-suite/ref/ngspice.tsv"
  "examples/16-nl-op-suite/spice/diode-bias.cir"
  "examples/16-nl-op-suite/spice/diode-series.cir"
  "examples/16-nl-op-suite/spice/rectifier.cir"
  "examples/16-nl-op-suite/spice/bjt-ce.cir"
  "notes/nl-op-compare.md"
  "scripts/compare-ngspice.sh"
  "scripts/vlm-extract.py"
  "scripts/from-image.sh"
  "scripts/run-aura.sh"
  "scripts/run-all.sh"
  "scripts/check-structure.sh"
)

missing=0
for f in "${required[@]}"; do
  if [[ -f "$f" ]]; then
    echo "  OK  $f"
  else
    echo "  MISSING  $f"
    missing=1
  fi
done

if [[ "$missing" -ne 0 ]]; then
  echo "Structure check FAILED" >&2
  exit 1
fi

echo "Structure OK (no Aura binary required)."
